from PyQt5.QtWidgets import QWidget, QLabel, QTextEdit, QLineEdit, QGridLayout, QPushButton


class OutsideAttributes(QWidget):
    def __init__(self, entries_window):
        super().__init__()
        self.entries_window = entries_window

        self.body_language_label = QLabel('Typical bodylanguage:')
        self.body_language_input = QTextEdit()
        self.clothes_style_label = QLabel('Typical clothes style:')
        self.clothes_style_input = QTextEdit()
        self.hygiene_label = QLabel('Typical hygiene:')
        self.hygiene_input = QLineEdit()
        self.sexual_orientation_label = QLabel('Sexual orientation:')
        self.sexual_orientation_input = QLineEdit()
        self.studying_behaviour_label = QLabel('Studying behaviour:')
        self.studying_behaviour_input = QTextEdit()
        self.loyalty_label = QLabel('Typical loyalty behaviour:')
        self.loyalty_input = QTextEdit()
        self.current_job_label = QLabel('Current job:')
        self.current_job_input = QLineEdit()
        self.job_history_label = QLabel('Job history:')
        self.job_history_input = QTextEdit()
        self.political_strategies_label = QLabel('Political strategies employed:')
        self.political_strategies_input = QTextEdit()
        self.projects_undertaken_label = QLabel('Projects undertaken:')
        self.projects_undertaken_input = QTextEdit()
        self.successful_projects_label = QLabel('Successful projects:')
        self.successful_projects_input = QTextEdit()
        self.failed_projects_label = QLabel('Failed projects')
        self.failed_projects_input = QTextEdit()
        self.social_style_label = QLabel('Typical social style:')
        self.social_style_input = QTextEdit()
        self.base_trust_label = QLabel('Base trust in the world:')
        self.base_trust_input = QLineEdit()
        self.phone_usage_label = QLabel('Phone usage behaviour:')
        self.phone_usage_input = QLineEdit()
        self.social_media_usage_label = QLabel('Social media usage behaviour:')
        self.social_media_usage_input = QTextEdit()
        self.add_button = QPushButton('Add')
        self.add_button.setMinimumWidth(130)
        self.back_button = QPushButton('Back')

        layout = QGridLayout()
        layout.addWidget(self.body_language_label, 0, 0, 1, 1)
        layout.addWidget(self.body_language_input, 0, 1, 1, 1)
        layout.addWidget(self.clothes_style_label, 1, 0, 1, 1)
        layout.addWidget(self.clothes_style_input, 1, 1, 1, 1)
        layout.addWidget(self.hygiene_label, 2, 0, 1, 1)
        layout.addWidget(self.hygiene_input, 2, 1, 1, 1)
        layout.addWidget(self.sexual_orientation_label, 3, 0, 1, 1)
        layout.addWidget(self.sexual_orientation_input, 3, 1, 1, 1)
        layout.addWidget(self.studying_behaviour_label, 4, 0, 1, 1)
        layout.addWidget(self.studying_behaviour_input, 4, 1, 1, 1)
        layout.addWidget(self.loyalty_label, 5, 0, 1, 1)
        layout.addWidget(self.loyalty_input, 5, 1, 1, 1)
        layout.addWidget(self.current_job_label, 6, 0, 1, 1)
        layout.addWidget(self.current_job_input, 6, 1, 1, 1)
        layout.addWidget(self.job_history_label, 7, 0, 1, 1)
        layout.addWidget(self.job_history_input, 7, 1, 1, 1)
        layout.addWidget(self.political_strategies_label, 8, 0, 1, 1)
        layout.addWidget(self.political_strategies_input, 8, 1, 1, 1)
        layout.addWidget(self.projects_undertaken_label, 9, 0, 1, 1)
        layout.addWidget(self.projects_undertaken_input, 9, 1, 1, 1)
        layout.addWidget(self.successful_projects_label, 10, 0, 1, 1)
        layout.addWidget(self.successful_projects_input, 10, 1, 1, 1)
        layout.addWidget(self.failed_projects_label, 11, 0, 1, 1)
        layout.addWidget(self.failed_projects_input, 11, 1, 1, 1)
        layout.addWidget(self.social_style_label, 12, 0, 1, 1)
        layout.addWidget(self.social_style_input, 12, 1, 1, 1)
        layout.addWidget(self.base_trust_label, 13, 0, 1, 1)
        layout.addWidget(self.base_trust_input, 13, 1, 1, 1)
        layout.addWidget(self.phone_usage_label, 14, 0, 1, 1)
        layout.addWidget(self.phone_usage_input, 14, 1, 1, 1)
        layout.addWidget(self.social_media_usage_label, 15, 0, 1, 1)
        layout.addWidget(self.social_media_usage_input, 15, 1, 1, 1)
        layout.addWidget(self.add_button, 0, 2, 1, 1)
        layout.addWidget(self.back_button, 1, 2, 1, 1)

        self.setLayout(layout)
